import type { Config } from 'tailwindcss'

const config: Config = {
  darkMode: ['class'],
  content: [
    './pages/**/*.{ts,tsx}',
    './components/**/*.{ts,tsx}',
    './app/**/*.{ts,tsx}',
    './lib/**/*.{ts,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        background: {
          DEFAULT: 'var(--background)',
          secondary: 'var(--background-secondary)',
          surface: 'var(--background-surface)',
        },
        foreground: 'var(--foreground)',
        card: {
          DEFAULT: 'var(--card)',
          foreground: 'var(--card-foreground)',
        },
        popover: {
          DEFAULT: 'var(--popover)',
          foreground: 'var(--popover-foreground)',
        },
        primary: {
          DEFAULT: 'var(--primary)',
          foreground: 'var(--primary-foreground)',
        },
        secondary: {
          DEFAULT: 'var(--secondary)',
          foreground: 'var(--secondary-foreground)',
        },
        muted: {
          DEFAULT: 'var(--muted)',
          foreground: 'var(--muted-foreground)',
        },
        accent: {
          DEFAULT: 'var(--accent)',
          foreground: 'var(--accent-foreground)',
        },
        destructive: {
          DEFAULT: 'var(--destructive)',
          foreground: 'var(--destructive-foreground)',
        },
        border: 'var(--border)',
        input: 'var(--input)',
        ring: 'var(--ring)',
        gold: {
          50: '#FFF9E6', 100: '#FFF0BF', 200: '#FFE080', 300: '#FFD040',
          400: '#FFBF00', 500: '#C9A84C', 600: '#A07830', 700: '#7A5820',
          800: '#543B10', 900: '#2E1E00',
        },
        emerald: {
          DEFAULT: '#2D8653',
          light: '#3DAA6A',
          dark: '#1E5C39',
        },
        crimson: {
          DEFAULT: '#8B2635',
          light: '#B03344',
          dark: '#5C1A25',
        },
        arcane: {
          DEFAULT: '#4A1C8B',
          light: '#6428B8',
          dark: '#310F5E',
        },
        // Stitch "Alea dos" design system colors
        'inverse-surface': '#e5e2e1',
        'outline': '#a08d80',
        'on-surface': '#e5e2e1',
        'on-surface-variant': '#d8c3b4',
        'surface-container-high': '#2a2a2a',
        'on-primary': '#4d2700',
        'surface-container-highest': '#353534',
        'surface-dim': '#131313',
        'surface-bright': '#393939',
        'tertiary': '#cac99f',
        'on-background': '#e5e2e1',
        'error': '#ffb4ab',
        'surface': '#131313',
        'surface-variant': '#353534',
        'outline-variant': '#524439',
        'surface-container-low': '#1c1b1b',
        'primary-container': '#c8803f',
        'secondary-container': '#5a403f',
        'surface-container': '#201f1f',
        'surface-container-lowest': '#0e0e0e',
        'on-primary-container': '#ffdcc2',
        'on-secondary': '#422020',
        'on-secondary-container': '#ffdad8',
        'on-tertiary': '#333200',
        'tertiary-container': '#4a4900',
        'on-tertiary-container': '#e6e58a',
        'on-error': '#690005',
        'on-error-container': '#ffdad6',
        'scrim': '#000000',
        'shadow': '#000000',
        'primary-fixed': '#ffdcc2',
        'primary-fixed-dim': '#ffb77b',
        'on-primary-fixed': '#2d1200',
        'on-primary-fixed-variant': '#c8803f',
        'secondary-fixed': '#ffdad8',
        'secondary-fixed-dim': '#e2bebb',
        'on-secondary-fixed': '#2c1514',
        'on-secondary-fixed-variant': '#5a403f',
        'tertiary-fixed': '#e6e58a',
        'tertiary-fixed-dim': '#cac99f',
        'on-tertiary-fixed': '#1e1d00',
        'on-tertiary-fixed-variant': '#4a4900',
        'inverse-on-surface': '#313030',
        'inverse-primary': '#8c4a00',
      },
      fontFamily: {
        cinzel: ['Cinzel', 'serif'],
        inter: ['Inter', 'sans-serif'],
        crimson: ['Crimson Text', 'serif'],
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      keyframes: {
        'accordion-down': { from: { height: '0' }, to: { height: 'var(--radix-accordion-content-height)' } },
        'accordion-up': { from: { height: 'var(--radix-accordion-content-height)' }, to: { height: '0' } },
        shimmer: { '0%': { transform: 'translateX(-100%)' }, '100%': { transform: 'translateX(100%)' } },
        glow: { '0%, 100%': { opacity: '1' }, '50%': { opacity: '0.5' } },
      },
      animation: {
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up': 'accordion-up 0.2s ease-out',
        shimmer: 'shimmer 2s infinite',
        glow: 'glow 2s ease-in-out infinite',
      },
    },
  },
  plugins: [require('tailwindcss-animate')],
}
export default config
